AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  github-actions-with-aws-sam

  Sample SAM Template for github-actions-with-aws-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Parameters:
  DatabaseName:
    Type: String

Resources:
  ScheduledFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        ScheduledLambdaExecution:
          Type: Schedule
          Properties:
            Schedule: cron(0 9,21 * * ? *) # 9am and 9pm
            Enabled: True
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: "OVO_USER"
        - SSMParameterReadPolicy:
            ParameterName: "OVO_PASS"
        - Statement:
          - Sid: TimestreamDescribeEndpoints
            Effect: Allow
            Action:
              - timestream:DescribeEndpoints
            Resource: "*"
        - Statement:
          - Sid: TimestreamWrite
            Effect: Allow
            Action:
              - timestream:WriteRecords
            Resource:
              !Sub 'arn:aws:timestream:${AWS::Region}:${AWS::AccountId}:database/${DatabaseName}/*'


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#  HelloWorldApi:
#    Description: "API Gateway endpoint URL for Prod stage for Ovo Energy function"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ScheduledFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt ScheduledFunction.Arn
  ScheduledFunctionIamRole:
    Description: "Implicit IAM Role created for scheduled function"
    Value: !GetAtt ScheduledFunction.Arn
